name: TakaProject
scan:
  number: 203
  name: Scan_0203
detector:
  shape:
  - 1062
  - 1028
scans:
  Scan_0203:
    dir: /mnt/c/Users/trobson/OneDrive - Argonne National Laboratory/2026-1_Luo/raw_scans/Scan_0203/XRD
    frames_dir: /mnt/c/Users/trobson/OneDrive - Argonne National Laboratory/2026-1_Luo/raw_scans/Scan_0203/XRD
    n_files: 151
    n_frames: 25217
    shape:
    - 1062
    - 1028
paths:
  raw_dir: Raw
  binned_dir: Binned
  metadata_dir: Metadata
  labels_dir: Labels
  figures_dir: Figures
  cvevolve_dir: CVEvolve
data_sources:
  raw_root: null
  position_root: null
  raw_scan_dir: null
  position_csv: null
  tth_map: /mnt/c/Users/trobson/OneDrive - Argonne National Laboratory/2026-1_Luo/tth.tiff
  reflections: null
  grid_mapping: null
  detector_script: null
bins: {}
tracking:
  enabled: true
  mlflow_tracking_uri: file:///mnt/c/Users/trobson/OneDrive - Argonne National Laboratory/2026-1_Luo/TakaTest/TakaProject/CVEvolve/mlruns
