"""Save Algorithm: freeze a tuned detector variant into a runnable .py.

When a user dials in a good sensitivity (+ optional noise reduction) on top of a
base detector, this writes a new module into the algorithm library that:

  1. bakes in the chosen sensitivity (SNR threshold),
  2. optionally applies a noise-reduction step in the cleaning stage,
  3. delegates everything else to the base detector,

conforming to the detector contract that ``core.processing`` imports
(``precompute_tth``, ``radial_median_subtract``, ``fast_tophat``,
``build_tth_band_masks``, ``detect_in_band``). The new module is registered in
``PeakAlgorithms/catalog.json`` so it shows up in ``xrd-app detectors`` and the
GUI dropdowns.

Noise reduction reproduces the View/Label tool's radial (2theta) background
subtraction: ``noise_reduction`` names one of the models in
``NoiseReduction/noise_reduction_algorithms.py`` ("gaussian", "split_gaussian",
"skewed_gaussian", "fourier") and ``noise_strength``/``noise_shift`` carry the
Strength/Shift slider values. The generated wrapper calls that library's
``reduce_noise`` per image before the base detector's own cleaning, so the saved
detector cleans exactly as the displayed image did.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

# Wrapper source template. ``{base}`` is imported by module name; the base lives
# in the flat ``PeakAlgorithms/`` root, which ``core.io.load_module`` puts on
# sys.path during dynamic import (along with NoiseReduction/).
_TEMPLATE = '''\
# Auto-generated by xrd-app "Save Algorithm" — do not edit by hand.
# base:        {base}
# sensitivity: SNR={sensitivity}
# noise:       {noise} (strength={strength}, shift={shift})
# display:     log={log_scale}, clip_pct=({clip_lo}, {clip_hi})
import importlib as _importlib
import numpy as _np
# Imported by name (digit-safe, e.g. "5x5_..."); core.io.load_module puts the
# flat PeakAlgorithms/ root on sys.path so this resolves.
_base = _importlib.import_module("{base}")

SENSITIVITY = {sensitivity}        # baked-in SNR threshold
NOISE_REDUCTION = {noise!r}        # None, or a radial background model name
NOISE_STRENGTH = {strength}        # Strength slider (background subtraction scale)
NOISE_SHIFT = {shift}              # Shift slider (additive background offset)
LOG_SCALE = {log_scale!r}          # apply log1p before detection (display parity)
CLIP_LO_PCT = {clip_lo!r}          # contrast percentile bounds (per image), or None
CLIP_HI_PCT = {clip_hi!r}

# Re-export the unchanged contract functions from the base detector.
precompute_tth = _base.precompute_tth
fast_tophat = _base.fast_tophat
build_tth_band_masks = _base.build_tth_band_masks


def radial_median_subtract(image, tth_data):
    img = image
    if NOISE_REDUCTION:
        # Reproduce the View/Label tool's radial (2theta) background subtraction:
        # fit the chosen model to this image's radial profile and subtract it,
        # then run the base detector's own cleaning on the result —
        # i.e. base_clean(noise_reduce(image)). tth_data already carries the 2theta
        # binning; reduce_noise only uses its tth_map arg for output shape, so the
        # image itself (same shape) is passed there.
        from noise_reduction_algorithms import reduce_noise
        cleaned, _bg, _fit = reduce_noise(
            img, img, tth_data["edges"], tth_data["centers"],
            tth_data["n_bins"], tth_data["indices"], tth_data["counts"],
            algorithm=NOISE_REDUCTION, strength=NOISE_STRENGTH, shift=NOISE_SHIFT)
        img = _np.clip(cleaned, 0, None)
    # Match the "Run on displayed image (filtered/clipped)" transform: log1p
    # then clip to the contrast percentile bounds, recomputed per image so the
    # bounds adapt to each bin (the GUI vmin/vmax are per-image percentiles).
    if LOG_SCALE:
        img = _np.log1p(_np.clip(img, 0, None))
    if CLIP_LO_PCT is not None and CLIP_HI_PCT is not None:
        finite = img[_np.isfinite(img)]
        if finite.size:
            lo = float(_np.percentile(finite, CLIP_LO_PCT))
            hi = float(_np.percentile(finite, CLIP_HI_PCT))
            img = _np.clip(img, lo, hi)
    return _base.radial_median_subtract(img, tth_data)


def detect_in_band(tophat_image, cleaned_image, band_mask, label,
                   snr_threshold=4.0, **kwargs):
    # Ignore the caller's SNR; use the baked-in sensitivity.
    return _base.detect_in_band(tophat_image, cleaned_image, band_mask, label,
                                snr_threshold=SENSITIVITY, **kwargs)
'''


def make_name(base: str, sensitivity, noise_reduction: Optional[str],
              noise_strength: float = 1.0, noise_shift: float = 0.0,
              log_scale: bool = False, clip_lo_pct=None, clip_hi_pct=None) -> str:
    """Manual naming convention: ``<base>__sens<NN>__nr-<model|none>``.

    Non-default Strength/Shift and any display transforms (log / contrast clip)
    are appended so distinct settings don't collide on the same name.
    """
    def _f(v):
        return str(v).replace(".", "p").replace("-", "m")

    s = str(sensitivity).replace(".", "p")
    nr = (noise_reduction or "none").replace(" ", "-")
    name = f"{base}__sens{s}__nr-{nr}"
    if noise_reduction and (noise_strength != 1.0 or noise_shift != 0.0):
        name += f"__str{_f(noise_strength)}__sh{_f(noise_shift)}"
    if log_scale:
        name += "__log"
    if clip_lo_pct is not None and clip_hi_pct is not None:
        name += f"__clip{_f(clip_lo_pct)}-{_f(clip_hi_pct)}"
    return name


def _sanitize(name: str) -> str:
    """Make a name a valid Python module stem."""
    stem = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if stem and stem[0].isdigit():
        stem = "a" + stem
    return stem


def register_in_catalog(catalog_path, entry: dict) -> None:
    """Insert/replace an entry in catalog.json keyed by (name, bin_size)."""
    catalog_path = Path(catalog_path)
    if catalog_path.exists():
        with open(catalog_path) as f:
            cat = json.load(f)
    else:
        cat = {"detectors": []}
    dets = cat.setdefault("detectors", [])
    dets[:] = [d for d in dets
               if not (d.get("name") == entry["name"] and d.get("bin_size") == entry["bin_size"])]
    dets.append(entry)
    with open(catalog_path, "w") as f:
        json.dump(cat, f, indent=2)


def save_algorithm(base: str, *, sensitivity, bin_size: int,
                   noise_reduction: Optional[str] = None,
                   noise_strength: float = 1.0, noise_shift: float = 0.0,
                   log_scale: bool = False, clip_lo_pct=None, clip_hi_pct=None,
                   name: Optional[str] = None, kind: str = "peak",
                   source: str = "manual", holdout_f1=None, holdout_f2=None,
                   algorithms_dir=None) -> Path:
    """Generate and register a wrapper detector. Returns the written .py path.

    The library is flat and bin-agnostic. A *manual* save lands as a loose
    ``PeakAlgorithms/<stem>.py``; an *automated* save (``source`` other than
    "manual", e.g. CVEvolve) gets its own folder ``PeakAlgorithms/<stem>/`` with
    a ``detector.py`` so it can carry support files alongside it. ``bin_size`` is
    recorded only as metadata (the same algorithm runs on any bin).

    ``algorithms_dir`` defaults to the bundled ``PeakAlgorithms/`` directory.
    """
    if algorithms_dir is None:
        algorithms_dir = Path(__file__).resolve().parent.parent / "PeakAlgorithms"
    algorithms_dir = Path(algorithms_dir)
    algorithms_dir.mkdir(parents=True, exist_ok=True)

    stem = _sanitize(name or make_name(base, sensitivity, noise_reduction,
                                       noise_strength, noise_shift,
                                       log_scale, clip_lo_pct, clip_hi_pct))
    automated = source != "manual"
    if automated:
        out_dir = algorithms_dir / stem
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "detector.py"
        rel_file = f"{stem}/detector.py"
    else:
        out_path = algorithms_dir / f"{stem}.py"
        rel_file = f"{stem}.py"
    out_path.write_text(_TEMPLATE.format(
        base=base, sensitivity=sensitivity, noise=noise_reduction,
        strength=noise_strength, shift=noise_shift, log_scale=log_scale,
        clip_lo=clip_lo_pct, clip_hi=clip_hi_pct))

    register_in_catalog(algorithms_dir / "catalog.json", {
        "name": stem,
        "bin_size": None,
        "file": rel_file,
        "role": "detector",
        "kind": kind,
        "holdout_f1": holdout_f1,
        "holdout_f2": holdout_f2,
        "source": source,
        "base": base,
        "sensitivity": sensitivity,
        "noise_reduction": noise_reduction,
        "noise_strength": noise_strength,
        "noise_shift": noise_shift,
        "log_scale": log_scale,
        "clip_lo_pct": clip_lo_pct,
        "clip_hi_pct": clip_hi_pct,
    })
    return out_path
