"""Save Algorithm: freeze a tuned detector variant into a runnable .py.

When a user dials in a good sensitivity (+ optional noise reduction) on top of a
base detector, this writes a new module into the algorithm library that:

  1. bakes in the chosen sensitivity (SNR threshold),
  2. optionally applies a noise-reduction step in the cleaning stage,
  3. delegates everything else to the base detector,

conforming to the detector contract that ``core.processing`` imports
(``precompute_tth``, ``radial_median_subtract``, ``fast_tophat``,
``build_tth_band_masks``, ``detect_in_band``). The new module is registered in
``PeakAlgorithms/catalog.json`` so it shows up in ``xrd-app detectors`` and the
GUI dropdowns.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

# Wrapper source template. ``{base}`` is imported by module name; the base lives
# in the flat ``PeakAlgorithms/`` root, which ``core.io.load_module`` puts on
# sys.path during dynamic import (along with NoiseReduction/).
_TEMPLATE = '''\
# Auto-generated by xrd-app "Save Algorithm" — do not edit by hand.
# base:        {base}
# sensitivity: SNR={sensitivity}
# noise:       {noise}
import importlib as _importlib
# Imported by name (digit-safe, e.g. "5x5_..."); core.io.load_module puts the
# flat PeakAlgorithms/ root on sys.path so this resolves.
_base = _importlib.import_module("{base}")

SENSITIVITY = {sensitivity}        # baked-in SNR threshold
NOISE_REDUCTION = {noise!r}        # None, or a noise-reduction label

# Re-export the unchanged contract functions from the base detector.
precompute_tth = _base.precompute_tth
fast_tophat = _base.fast_tophat
build_tth_band_masks = _base.build_tth_band_masks


def radial_median_subtract(image, tth_data):
    cleaned = _base.radial_median_subtract(image, tth_data)
    if NOISE_REDUCTION:
        from scipy.ndimage import gaussian_filter
        cleaned = gaussian_filter(cleaned, sigma=1.0)
    return cleaned


def detect_in_band(tophat_image, cleaned_image, band_mask, label,
                   snr_threshold=4.0, **kwargs):
    # Ignore the caller's SNR; use the baked-in sensitivity.
    return _base.detect_in_band(tophat_image, cleaned_image, band_mask, label,
                                snr_threshold=SENSITIVITY, **kwargs)
'''


def make_name(base: str, sensitivity, noise_reduction: Optional[str]) -> str:
    """Manual naming convention: ``<base>__sens<NN>__nr-<module|none>``."""
    s = str(sensitivity).replace(".", "p")
    nr = (noise_reduction or "none").replace(" ", "-")
    return f"{base}__sens{s}__nr-{nr}"


def _sanitize(name: str) -> str:
    """Make a name a valid Python module stem."""
    stem = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if stem and stem[0].isdigit():
        stem = "a" + stem
    return stem


def register_in_catalog(catalog_path, entry: dict) -> None:
    """Insert/replace an entry in catalog.json keyed by (name, bin_size)."""
    catalog_path = Path(catalog_path)
    if catalog_path.exists():
        with open(catalog_path) as f:
            cat = json.load(f)
    else:
        cat = {"detectors": []}
    dets = cat.setdefault("detectors", [])
    dets[:] = [d for d in dets
               if not (d.get("name") == entry["name"] and d.get("bin_size") == entry["bin_size"])]
    dets.append(entry)
    with open(catalog_path, "w") as f:
        json.dump(cat, f, indent=2)


def save_algorithm(base: str, *, sensitivity, bin_size: int,
                   noise_reduction: Optional[str] = None,
                   name: Optional[str] = None, kind: str = "peak",
                   source: str = "manual", holdout_f1=None, holdout_f2=None,
                   algorithms_dir=None) -> Path:
    """Generate and register a wrapper detector. Returns the written .py path.

    The library is flat and bin-agnostic. A *manual* save lands as a loose
    ``PeakAlgorithms/<stem>.py``; an *automated* save (``source`` other than
    "manual", e.g. CVEvolve) gets its own folder ``PeakAlgorithms/<stem>/`` with
    a ``detector.py`` so it can carry support files alongside it. ``bin_size`` is
    recorded only as metadata (the same algorithm runs on any bin).

    ``algorithms_dir`` defaults to the bundled ``PeakAlgorithms/`` directory.
    """
    if algorithms_dir is None:
        algorithms_dir = Path(__file__).resolve().parent.parent / "PeakAlgorithms"
    algorithms_dir = Path(algorithms_dir)
    algorithms_dir.mkdir(parents=True, exist_ok=True)

    stem = _sanitize(name or make_name(base, sensitivity, noise_reduction))
    automated = source != "manual"
    if automated:
        out_dir = algorithms_dir / stem
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "detector.py"
        rel_file = f"{stem}/detector.py"
    else:
        out_path = algorithms_dir / f"{stem}.py"
        rel_file = f"{stem}.py"
    out_path.write_text(_TEMPLATE.format(
        base=base, sensitivity=sensitivity, noise=noise_reduction))

    register_in_catalog(algorithms_dir / "catalog.json", {
        "name": stem,
        "bin_size": None,
        "file": rel_file,
        "role": "detector",
        "kind": kind,
        "holdout_f1": holdout_f1,
        "holdout_f2": holdout_f2,
        "source": source,
        "base": base,
        "sensitivity": sensitivity,
        "noise_reduction": noise_reduction,
    })
    return out_path
